/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as SuitabilityRouteImport } from './routes/suitability'
import { Route as SoilRouteImport } from './routes/soil'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ParcelsRouteImport } from './routes/parcels'
import { Route as GisRouteImport } from './routes/gis'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as ExpansionRouteImport } from './routes/expansion'
import { Route as DiversificationRouteImport } from './routes/diversification'
import { Route as DistributionRouteImport } from './routes/distribution'
import { Route as CropMappingRouteImport } from './routes/crop-mapping'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as IndexRouteImport } from './routes/index'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitabilityRoute = SuitabilityRouteImport.update({
  id: '/suitability',
  path: '/suitability',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilRoute = SoilRouteImport.update({
  id: '/soil',
  path: '/soil',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelsRoute = ParcelsRouteImport.update({
  id: '/parcels',
  path: '/parcels',
  getParentRoute: () => rootRouteImport,
} as any)
const GisRoute = GisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpansionRoute = ExpansionRouteImport.update({
  id: '/expansion',
  path: '/expansion',
  getParentRoute: () => rootRouteImport,
} as any)
const DiversificationRoute = DiversificationRouteImport.update({
  id: '/diversification',
  path: '/diversification',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributionRoute = DistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const CropMappingRoute = CropMappingRouteImport.update({
  id: '/crop-mapping',
  path: '/crop-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/campaigns': typeof CampaignsRoute
  '/crop-mapping': typeof CropMappingRoute
  '/distribution': typeof DistributionRoute
  '/diversification': typeof DiversificationRoute
  '/expansion': typeof ExpansionRoute
  '/farmer': typeof FarmerRoute
  '/gis': typeof GisRoute
  '/parcels': typeof ParcelsRoute
  '/reports': typeof ReportsRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/soil': typeof SoilRoute
  '/suitability': typeof SuitabilityRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/campaigns': typeof CampaignsRoute
  '/crop-mapping': typeof CropMappingRoute
  '/distribution': typeof DistributionRoute
  '/diversification': typeof DiversificationRoute
  '/expansion': typeof ExpansionRoute
  '/farmer': typeof FarmerRoute
  '/gis': typeof GisRoute
  '/parcels': typeof ParcelsRoute
  '/reports': typeof ReportsRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/soil': typeof SoilRoute
  '/suitability': typeof SuitabilityRoute
  '/weather': typeof WeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisory': typeof AdvisoryRoute
  '/campaigns': typeof CampaignsRoute
  '/crop-mapping': typeof CropMappingRoute
  '/distribution': typeof DistributionRoute
  '/diversification': typeof DiversificationRoute
  '/expansion': typeof ExpansionRoute
  '/farmer': typeof FarmerRoute
  '/gis': typeof GisRoute
  '/parcels': typeof ParcelsRoute
  '/reports': typeof ReportsRoute
  '/schemes': typeof SchemesRoute
  '/settings': typeof SettingsRoute
  '/soil': typeof SoilRoute
  '/suitability': typeof SuitabilityRoute
  '/weather': typeof WeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisory'
    | '/campaigns'
    | '/crop-mapping'
    | '/distribution'
    | '/diversification'
    | '/expansion'
    | '/farmer'
    | '/gis'
    | '/parcels'
    | '/reports'
    | '/schemes'
    | '/settings'
    | '/soil'
    | '/suitability'
    | '/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisory'
    | '/campaigns'
    | '/crop-mapping'
    | '/distribution'
    | '/diversification'
    | '/expansion'
    | '/farmer'
    | '/gis'
    | '/parcels'
    | '/reports'
    | '/schemes'
    | '/settings'
    | '/soil'
    | '/suitability'
    | '/weather'
  id:
    | '__root__'
    | '/'
    | '/advisory'
    | '/campaigns'
    | '/crop-mapping'
    | '/distribution'
    | '/diversification'
    | '/expansion'
    | '/farmer'
    | '/gis'
    | '/parcels'
    | '/reports'
    | '/schemes'
    | '/settings'
    | '/soil'
    | '/suitability'
    | '/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisoryRoute: typeof AdvisoryRoute
  CampaignsRoute: typeof CampaignsRoute
  CropMappingRoute: typeof CropMappingRoute
  DistributionRoute: typeof DistributionRoute
  DiversificationRoute: typeof DiversificationRoute
  ExpansionRoute: typeof ExpansionRoute
  FarmerRoute: typeof FarmerRoute
  GisRoute: typeof GisRoute
  ParcelsRoute: typeof ParcelsRoute
  ReportsRoute: typeof ReportsRoute
  SchemesRoute: typeof SchemesRoute
  SettingsRoute: typeof SettingsRoute
  SoilRoute: typeof SoilRoute
  SuitabilityRoute: typeof SuitabilityRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suitability': {
      id: '/suitability'
      path: '/suitability'
      fullPath: '/suitability'
      preLoaderRoute: typeof SuitabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil': {
      id: '/soil'
      path: '/soil'
      fullPath: '/soil'
      preLoaderRoute: typeof SoilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcels': {
      id: '/parcels'
      path: '/parcels'
      fullPath: '/parcels'
      preLoaderRoute: typeof ParcelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis': {
      id: '/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof GisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expansion': {
      id: '/expansion'
      path: '/expansion'
      fullPath: '/expansion'
      preLoaderRoute: typeof ExpansionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diversification': {
      id: '/diversification'
      path: '/diversification'
      fullPath: '/diversification'
      preLoaderRoute: typeof DiversificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribution': {
      id: '/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof DistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-mapping': {
      id: '/crop-mapping'
      path: '/crop-mapping'
      fullPath: '/crop-mapping'
      preLoaderRoute: typeof CropMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisoryRoute: AdvisoryRoute,
  CampaignsRoute: CampaignsRoute,
  CropMappingRoute: CropMappingRoute,
  DistributionRoute: DistributionRoute,
  DiversificationRoute: DiversificationRoute,
  ExpansionRoute: ExpansionRoute,
  FarmerRoute: FarmerRoute,
  GisRoute: GisRoute,
  ParcelsRoute: ParcelsRoute,
  ReportsRoute: ReportsRoute,
  SchemesRoute: SchemesRoute,
  SettingsRoute: SettingsRoute,
  SoilRoute: SoilRoute,
  SuitabilityRoute: SuitabilityRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
